### ISSUE TITLE
add filePath to videoRecordingFinished(); on AREventListener

### ISSUE THREAD

**Issue by memishood** [DeepARSDK/quickstart-android-java#13]
I wish i could get filePath which video was recorded over the videoRecordingFinished() looks like screenshotTaken(Bitmap var1)

**Comment by Sikter** [comment]
Hi, well you already know this since you have to set a path when the recording starts, here is the excerpt from our API docs:
**void startVideoRecording(String filePath)**
Starts video recording of the camera preview. The video will be the same size as SurfaceView. Video recording events can be observed through AREventListener implementation.
