### ISSUE TITLE
Dynamic filters

### ISSUE THREAD

**Issue by ajayparmar15** [DeepARSDK/quickstart-android-java#28]
How can i switch mask on face from the server link (dynamic filter on our server)
is the DeepAR support dynamic filter?

**Comment by amosogra** [comment]
Hey contact me, I can help you fix it. I did for my client.
floodcoding@gmail.com

**Comment by JelenaKB** [comment]
[switchEffect](https://s3.eu-west-1.amazonaws.com/sdk.developer.deepar.ai/doc/android/ai/deepar/ar/DeepAR.html#switchEffect-java.lang.String-java.io.InputStream-)(java.lang.String slot, java.io.InputStream inputStream)


You can load filters from a URL using this method:
Same as [switchEffect](https://s3.eu-west-1.amazonaws.com/sdk.developer.deepar.ai/doc/android/ai/deepar/ar/DeepAR.html#switchEffect-java.lang.String-java.lang.String-), but uses an [InputStream](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html) instead of a file path.
