### ISSUE TITLE
DeepAr support webrtc android native?

### ISSUE THREAD

**Issue by beheobong** [DeepARSDK/quickstart-android-java#35]

**Comment by rainbowdrg** [comment]
Hi @beheobong, are you success to integrate Deep AR with any webrtc? I also want to integrate Deep AR with Ant Media Server but can't found any solution.

**Comment by JelenaKB** [comment]
DeepAR can be integrated with video call APIs, you can use the Agora example as a reference for how the workflow goes.

The idea is to use DeepAR's output as an input to the video call stream, instead of the regular live camera feed﻿﻿.

We don't have a tutorial for your specific API but this approach should work﻿
